node: 100
server:
    port: 9090
    context-path: /
logging:
    level:
        com.ihs: DEBUG
datasource:
        name: ihsDataSourceName
        url: jdbc:mysql://localhost:3306/ihs?charset=UTF8&useSSL=false
        username: root
        password: tiger
        driverClassName: com.mysql.jdbc.Driver
        autoCommit: false
        minimumIdle: 20
        maximumPoolSize: 20
        connectionInitSql: select 1
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
spring:
    mvc.view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    freemarker:
        cache: false
        request-context-attribute: request
 
crossDomainFilter:
    origin: "*"
#multipart:
#    maxFileSize: 100M
#    maxRequestSize: 100M
#    datasource:

#          name: test
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/test
#          username: root
#          password: 123456
#          initialSize: 1
#          minIdle: 1
#          maxWait: 6000
#          maxActive: 20
#          timeBetweenEvictionRunsMillis: 60000
#          minEvictableIdleTimeMillis: 300000
#          validationQuery: select *
#          testWhileIdle: true
#          testOnBorrow: false
#          testOnReturn: false
#          filters: stat
#          poolPreparedStatements: true
#          maxOpenPreparedStatements: 20
#    redis:
#        host: localhost    # server host
#        password: balabala # server password
#        port: 6379         # connection port
#        pool:              # pool settings ...
#            max-idle: 8
#            min-idle: 0
#            max-active: 8
#            max-wait: -1
#mybatis:
#    config-location: classpath:mybatis-config.xml
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.links86.domain